
KERNDIR = ../../kern
GROUPFILE = groupings.txt
PROGRAM = ./groupit

example-list:
	$(PROGRAM) -e $(GROUPFILE) $(KERNDIR)

check:
	$(PROGRAM) $(GROUPFILE) $(KERNDIR)

doit:
	$(PROGRAM) -r $(GROUPFILE) $(KERNDIR)
