#!/usr/bin/perl

my @list1 = glob("*.sib");
my @list2 = glob("../*.sib");

my %L1;
my %L2;


foreach my $item (@list1) {
	$L1{$item} = 1;
}

foreach my $item (@list2) {
	$L2{$item} = 1;
}

print "CHECKING 1 against 2\n";
foreach my $item (@list1) {
	if (!$L2{"../$item"}) {
		print "$item is missing from list 2\n";
	}
}


print "CHECKING 2 against 1\n";
foreach my $item (@list2) {
	$item =~ s/.*\///;
	if (!$L1{$item}) {
		print "$item is missing from list 1\n";
	}
}

